blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/CloudQuish/pdffille_os/discussions
    about: Ask questions or start discussions.
  - name: Security
    url: https://github.com/CloudQuish/pdffille_os/security
    about: Report security vulnerabilities.
